name: update-index-html

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # 매일 오후 9시(UTC+09:00 고려)에 실행

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Run
        run: |
          python run.py \
            --login ${{ secrets.SECRET_LOGIN_URL }} \
            --id ${{ secrets.SECRET_ID }} \
            --password ${{ secrets.SECRET_PASSWORD }} \
            --url ${{ secrets.SECRET_DATA_URL }} \
            --element ${{ secrets.SECRET_ELEMENT }} \
            --output data.csv
          csvtotable data.csv index.html

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions@users.noreply.github.com'
          git add .
          git commit -m 'Update index.html'
          git push
