name: update-index-html

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # 매일 오후 9시(UTC+09:00 고려)에 실행

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: 시간 추가
        run: |
          echo "## 업데이트 시간" >> README.md
          echo "$(date +'%Y-%m-%d %H:%M:%S')" >> README.md

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions@users.noreply.github.com'
          git add .
          git commit -m '오늘 날짜 추가'
          git push
